Repository FRONTENDSCHOOL6/JIJO-cafe, pull requests merged in 2023-09, with the labels that each got.

#18 [ 공통 ] Tailwind CSS 커스텀 중단점 및 color 추가 / Jijo Spinner 제작 / 라우터 추가 수정 / 상태를 토글하는 useToggle Custom Hook / 반응형 헤더 / Link List 컴포넌트
  .eslintrc.cjs
  index.html
  public/logo.svg
  src/api/pocketbase.js
  src/assets/images/D.js
  src/assets/images/blog.svg
  src/assets/images/facebook.svg
  src/assets/images/instagram.svg
  src/assets/images/logoTitle.png
  src/components/D.js
  src/components/Hamburger.jsx
  src/components/JijoSpinner.jsx
  src/components/LinkList.jsx
  src/components/SignInModal.jsx
  src/hooks/useToggle.jsx
  src/layout/Header.jsx
  src/layout/Header/Header.jsx
  src/layout/Header/Header.module.css
  src/layout/RootLayout.jsx
  src/routes/routes.jsx
  src/store/D.js
  src/styles/tailwind.css
  src/utils/D.js
  src/views/Cart.jsx
  src/views/Customer.jsx
  src/views/D.js
  src/views/Drink.jsx
  src/views/Event.jsx
  src/views/Faq.jsx
  src/views/FindStore.jsx
  src/views/Food.jsx
  src/views/Main.jsx
  src/views/Notice.jsx
  src/views/Product.jsx
  src/views/SignIn.jsx
  src/views/SignUp.jsx
  tailwind.config.js
Labels: ✅ add, 💚 CSS, ✨ feat, 💙 react, ♻️ refactor, 🌠 core

#50 Pagination 마크업 및 기능 구현
  index.html
  src/components/Pagination/Pagination.jsx
  src/styles/tailwind.css
Labels: ✅ add, ✨ feat, 💙 react

#51 Notice
  src/components/Button.jsx
  src/views/Customer.jsx
  src/views/Faq.jsx
  src/views/Notice.jsx
  tailwind.config.js
Labels: ✨ feat, 🦁 modify

#64 useOutsideClickClose 커스텀 훅 / Zustand AuthStore 구상 / 회원가입 페이지 스타일링 완성
  src/components/Button.jsx
  src/components/CheckBox.jsx
  src/components/CheckboxButton.jsx
  src/components/DropDownLinkList.jsx
  src/components/Hamburger/Hamburger.module.css
  src/components/Input.jsx
  src/components/KakaoTalkSignInButton.jsx
  src/components/LinkList.jsx
  src/components/PageMainTitle.jsx
  src/components/SignInForm.jsx
  src/components/SignInModal.jsx
  src/hooks/useOutsideClickClose.jsx
  src/layout/Footer/Footer.jsx
  src/layout/Header/Header.jsx
  src/layout/Header/Header.module.css
  src/layout/Wrapper/SignUpFormWrapper.jsx
  src/store/store.js
  src/views/Drink.jsx
  src/views/Main.jsx
  src/views/Notice.jsx
  src/views/SignUp.jsx
  tailwind.config.js
Labels: ✅ add, 💚 CSS, ✨ feat, 💙 react, 🦁 modify, 🔨mark up

#82 Notice,logo추가,컴포넌트분리, 검색창구현
  index.html
  public/logo_black.svg
  public/logo_icon.svg
  public/logo_white.svg
  src/components/Button.jsx
  src/components/JijoCafeLogoTitle.jsx
  src/components/Notice/NoticeList.jsx
  src/components/Notice/NoticeSearchFilter.jsx
  src/components/PageMainTitle.jsx
  src/layout/Footer/Footer.jsx
  src/layout/Header/Header.module.css
  src/routes/routes.jsx
  src/utils/yyyymmddDate.js
  src/views/Notice.jsx
  src/views/NoticeDetail.jsx
Labels: ✅ add, 💚 CSS, ✨ feat, 💙 react, 🦁 modify

#92 Notice
  src/components/Button.jsx
  src/components/JijoError.jsx
  src/components/Notice/Detail.jsx
  src/components/Notice/NoticeList.jsx
  src/components/Notice/NoticeSearchFilter.jsx
  src/utils/getPbImageURL.js
  src/views/Notice.jsx
  src/views/NoticeDetail.jsx
  tailwind.config.js
Labels: ✅ add, 💚 CSS, ✨ feat, 🦁 modify, 🔨mark up

#94 회원가입 페이지 내 SignUp 함수 리팩토링 / 로그인 컴포넌트에서 로그인을 두번 클릭해야 로그인 되는 현상 해결 / 로그인 컴포넌트 카카오톡 로그인하기 구현
  .prettier.js
  package.json
  pnpm-lock.yaml
  src/components/Button.jsx
  src/components/CheckBox/CheckBox.jsx
  src/components/CheckboxButton.jsx
  src/components/DropDownLinkList.jsx
  src/components/EyeClosed.jsx
  src/components/EyeOpen.jsx
  src/components/Hamburger/Hamburger.module.css
  src/components/KakaoTalkSignInButton.jsx
  src/components/Products.jsx
  src/components/SignInModal.jsx
  src/hooks/usePocektBaseData.jsx
  src/layout/Header/Header.jsx
  src/layout/Header/Header.module.css
  src/layout/Wrapper/SignUpFormWrapper.jsx
  src/store/store.js
  src/utils/Validation.js
  src/utils/kakaoLogout.js
  src/views/Drink.jsx
  src/views/Main.jsx
  src/views/Notice.jsx
  src/views/SignUp.jsx
Labels: ✅ add, ✨ feat, 💙 react, ♻️ refactor, 📱pocketbase

#109 [매장찾기] 현재 위치 정보를 기반으로 KakaoMap 렌더링
  index.html
  package.json
  pnpm-lock.yaml
  src/components/FindStoreSearchForm.jsx
  src/components/Input.jsx
  src/components/KakaoMap.jsx
  src/components/KakaoTalkSignInButton.jsx
  src/components/SignInForm.jsx
  src/components/SignInModal.jsx
  src/hooks/useCurrnetLocation.jsx
  src/hooks/usePocektBaseData.jsx
  src/layout/Header/Header.jsx
  src/layout/Header/Header.module.css
  src/routes/routes.jsx
  src/utils/kakaoLogout.js
  src/views/Cart.jsx
  src/views/FindStore.jsx
  src/views/SignUp.jsx
  vite.config.js
Labels: ✨ feat, 💙 react, 🔒 setting

#110 Mainpage 마크업 및 스타일링
  package.json
  pnpm-lock.yaml
  src/App.jsx
  src/assets/images/main/cafe-jj-coffee.jpg
  src/assets/images/main/cafe-jj-coffee1.jpg
  src/assets/images/main/slide1.jpg
  src/assets/images/main/slide1_mobile.jpg
  src/assets/images/main/slide2.jpg
  src/assets/images/main/slide2_mobile.jpg
  src/assets/images/main/slide3.jpg
  src/assets/images/main/slide3_mobile.jpg
  src/assets/images/main/slide4.jpg
  src/assets/images/main/slide4_mobile.jpg
  src/assets/images/main/slide5.jpg
  src/assets/images/main/slide5_mobile.jpg
  src/assets/images/main/slide6.jpg
  src/assets/images/main/slide6_mobile.jpg
  src/assets/images/main/slide7.jpg
  src/assets/images/main/slide7_mobile.jpg
  src/components/MenuBubble.jsx
  src/components/Pagination.jsx
  src/layout/RootLayout.jsx
  src/routes/routes.jsx
  src/styles/Carousel.css
  src/styles/tailwind.css
  src/views/Main/Main.jsx
  src/views/Main/MainBanner .jsx
  src/views/Main/MainEvent.jsx
  src/views/Main/MainMenu.jsx
  src/views/Main/MainShopingMall.jsx
  src/views/Main/MainStore.jsx
  src/views/Main/MenuCarousel.jsx
  tailwind.config.js
Labels: ✅ add, 💚 CSS, ✨ feat, 💙 react, 🦁 modify, 🔨mark up

#122 Notice 공지등록,수정,삭제 기능구현 + 공지페이지 리액트쿼리 리팩토링
  src/components/Notice/DataForm.jsx
  src/components/Notice/Detail.jsx
  src/components/Notice/NoticeList.jsx
  src/components/Notice/NoticeSearchFilter.jsx
  src/routes/routes.jsx
  src/views/Faq.jsx
  src/views/Notice.jsx
  src/views/NoticeCreate.jsx
  src/views/NoticeDetail.jsx
  src/views/NoticeUpdate.jsx
Labels: ✅ add, ✨ feat, 🦁 modify, ♻️ refactor

#123 헤더 리팩토링 / useViewPort hook / 매장찾기 페이지 특정 키워드 마커 렌더링
  index.html
  package.json
  pnpm-lock.yaml
  src/components/FindStoreSearchForm.jsx
  src/components/Hamburger/Hamburger.module.css
  src/components/Input.jsx
  src/components/JijoCafeLogoTitle.jsx
  src/components/KakaoMap.jsx
  src/components/LogoLinks.jsx
  src/components/Notice/NoticeSearchFilter.jsx
  src/components/SignInModal.jsx
  src/hooks/useViewport.jsx
  src/layout/Footer/Footer.jsx
  src/layout/Header/CartLinkList.jsx
  src/layout/Header/DesktopHeader.jsx
  src/layout/Header/DesktopHeader.module.css
  src/layout/Header/Header.jsx
  src/layout/Header/Header.module.css
  src/layout/Header/TabletMobileHeader.jsx
  src/layout/Header/TabletMobileHeader.module.css
  src/layout/RootLayout.jsx
  src/store/store.js
  src/views/Cart.jsx
  src/views/FindStore.jsx
  src/views/Main/MainBanner .jsx
  src/views/Main/MenuCarousel.jsx
  src/views/SignUp.jsx
Labels: ✅ add, ✨ feat, 💙 react

#137 [매장찾기] 폼 내부 검색 기능 개발 / 헬멧 오픈그래프 유틸리티 컴포넌트
  public/JijoMarker.png
  src/api/pocketbase.js
  src/components/FindStoreSearchForm.jsx
  src/components/KakaoMap.jsx
  src/components/ReadingGlassesButton.jsx
  src/components/SignInModal.jsx
  src/layout/Header/DesktopHeader.jsx
  src/layout/Header/Header.jsx
  src/layout/Header/TabletMobileHeader.jsx
  src/layout/Header/TabletMobileHeader.module.css
  src/routes/routes.jsx
  src/store/store.js
  src/styles/tailwind.css
  src/utils/JiJoHelmet.jsx
  src/views/FindStore.jsx
Labels: ✅ add, ✨ feat, 💙 react

#144 최적화 작업 진행 / Header Framer-motion으로 애니메이션 효과 부여 / 카카오맵 초기 렌더링 이슈 수정
  .eslintrc.cjs
  package.json
  pnpm-lock.yaml
  src/App.jsx
  src/components/Event/EventContents.jsx
  src/components/FindStoreSearchForm.jsx
  src/components/KakaoMap.jsx
  src/components/Main/MenuCarousel.jsx
  src/components/Main/ShopingMallCarousel.jsx
  src/components/Notice/Detail.jsx
  src/components/Products.jsx
  src/components/SignInModal.jsx
  src/layout/Header/DesktopHeader.jsx
  src/layout/Header/DesktopHeader.module.css
  src/layout/Header/TabletMobileHeader.module.css
  src/layout/Wrapper/FindStoreSearchFormListWrapper.jsx
  src/routes/routes.jsx
  src/store/cartStore.js
  src/styles/tailwind.css
  src/utils/LazyImage.jsx
  src/views/Drink.jsx
  src/views/FindStore.jsx
  src/views/Food.jsx
  src/views/Main/MainBanner.jsx
  src/views/Main/MainEvent.jsx
  src/views/Main/MainShopingMall.jsx
  src/views/Main/MainStore.jsx
  src/views/Product.jsx
  src/views/SignUp.jsx
  tailwind.config.js
  vite.config.js
Labels: ✅ add, ✨ feat, 💙 react, ♻️ refactor, 🔒 setting

#146 Mainpage - 풀페이지 기능 구현 / 반응형 구현 / 메인텍스트 컨포넌트 분리
  package.json
  pnpm-lock.yaml
  src/assets/images/main/nextArrow.png
  src/components/Main/MainPageText.jsx
  src/components/Main/MainSubText.jsx
  src/components/Main/MainpageTitle.jsx
  src/components/Main/MenuCarousel.jsx
  src/components/Main/ShopingMallCarousel.jsx
  src/styles/Carousel.css
  src/styles/Main.module.css
  src/styles/tailwind.css
  src/views/Main/Main.jsx
  src/views/Main/MainBanner.jsx
  src/views/Main/MainEvent.jsx
  src/views/Main/MainMenu.jsx
  src/views/Main/MainShopingMall.jsx
  src/views/Main/MainStore.jsx
  tailwind.config.js
Labels: ✅ add

#153 게시글 수정후 리스트에 반영, 검색버튼 클릭후 input 문구, 관리자권한 변경
  src/components/Notice/Detail.jsx
  src/components/Notice/SelectSearchFilter.jsx
  src/views/Faq.jsx
  src/views/FaqDetail.jsx
  src/views/Notice.jsx
  src/views/NoticeDetail.jsx
Labels: 🐛 bug

#164 faq ,notice 뮤테이션으로 리팩토링, 메뉴페이지 페이지네이션 적용
  src/App.jsx
  src/api/pockets/useQueryPocketBase.js
  src/components/Categories.jsx
  src/components/Notice/TableListPagination.jsx
  src/components/Products.jsx
  src/layout/Header/DesktopHeader.jsx
  src/layout/Header/TabletMobileHeader.jsx
  src/views/Customer/Customer.jsx
  src/views/Customer/CustomerCreate.jsx
  src/views/Drink.jsx
  src/views/Faq.jsx
  src/views/FaqCreate.jsx
  src/views/FaqDetail.jsx
  src/views/FaqUpdate.jsx
  src/views/Food.jsx
  src/views/Notice.jsx
  src/views/NoticeCreate.jsx
  src/views/NoticeDetail.jsx
  src/views/NoticeUpdate.jsx
  src/views/Product.jsx
Labels: ✨ feat

#165 [공통] 폰트 경로 수정 / 깃허브 로그인 구현(진행중) / 모달 CSS 리팩토링
  index.html
  public/github.svg
  src/components/EyeOpen.jsx
  src/components/GithubSignInButton.jsx
  src/components/KakaoTalkSignInButton.jsx
  src/components/Main/MainpageTitle.jsx
  src/components/Notice/Detail.jsx
  src/components/Products.jsx
  src/components/SignInModal.jsx
  src/hooks/usePocektBaseData.jsx
  src/layout/Header/DesktopHeader.module.css
  src/layout/Header/TabletMobileHeader.jsx
  src/layout/Wrapper/ButtonWrapper.jsx
  src/layout/Wrapper/FindStoreSearchFormListWrapper.jsx
  src/store/store.js
  src/styles/tailwind.css
  src/views/EventDetail.jsx
  src/views/FindStore.jsx
  stats.html
  vite.config.js
Labels: 💚 CSS, ✨ feat, 💙 react, 🦁 modify

#166 Mainpage 와 Eventpage 기능 추가 및 마크업, 스타일링 수정
  pnpm-lock.yaml
  src/components/Event/EventContent.jsx
  src/components/Event/EventContents.jsx
  src/components/Event/EventPageNation.jsx
  src/components/Event/EventPagination.jsx
  src/components/Event/EventSearchForm.jsx
  src/components/Event/EventTab.jsx
  src/components/Event/TabContent.jsx
  src/components/Event/TabContents.jsx
  src/components/Main/MenuCarousel.jsx
  src/components/Main/ShopingMallCarousel.jsx
  src/styles/Carousel.css
  src/styles/tailwind.css
  src/views/Event.jsx
  src/views/EventDetail.jsx
  src/views/Main/MainBanner.jsx
  src/views/Main/MainEvent.jsx
  src/views/Main/MainMenu.jsx
  src/views/Main/MainShopingMall.jsx
  src/views/Main/MainStore.jsx
Labels: ✅ add, 💚 CSS, 🔥 remove, ✨ feat, 💙 react, 🦁 modify, ♻️ refactor, 🔨mark up

#167 [merge] merge to develop
  src/components/Cart/OrderListItem.jsx
  src/components/Cart/StoreChangeModal.jsx
  src/components/Categories.jsx
  src/components/Event/EventContent.jsx
  src/components/Event/EventTab.jsx
  src/components/Event/TabContents.jsx
  src/components/Main/MainPageText.jsx
  src/components/Main/MainTitleText.jsx
  src/components/Main/MenuCarousel.jsx
  src/components/Notice/TableListPagination.jsx
  src/components/Products.jsx
  src/components/RadioButton/RadioButton.jsx
  src/views/FaqDetail.jsx
  src/views/Food.jsx
Labels: 🌠 core

#168 [로그인] SignIn Modal 로그인 시 컴포넌트 사라지게 변경
  src/components/FindStoreSearchForm.jsx
  src/components/GithubSignInButton.jsx
  src/components/KakaoMap.jsx
  src/components/SignInModal.jsx
  src/hooks/usePaginationQuery.js
  src/layout/Header/DesktopHeader.jsx
  src/views/FindStore.jsx
  src/views/SignUp.jsx
Labels: 💙 react, 🦁 modify

#179 헤더 스타일 클래스 추가/ 이벤트 페이지 탭 기능 수정
  src/components/Event/EventTab.jsx
  src/layout/Header/DesktopHeader.jsx
Labels: 🦁 modify

#181 Findstore
  src/api/pockets/Pagination.jsx
  src/components/Cart/OrderListItem.jsx
  src/components/FindStoreSearchForm.jsx
  src/components/GithubSignInButton.jsx
  src/components/LogoLinks.jsx
  src/components/Products.jsx
  src/components/SignInModal.jsx
  src/layout/Footer/Footer.jsx
  src/layout/Header/CartLinkList.jsx
  src/utils/LazyImage.jsx
  src/views/Cart.jsx
  src/views/Drink.jsx
Labels: ✨ feat, 💙 react, 📱pocketbase

#182 [이벤트 디테일] 이전 다음 페이지 이동 기능 추가
  src/components/Event/EventContent.jsx
  src/views/EventDetail.jsx
Labels: ✨ feat

#184 🦁 modify : CartLinkList 장바구니 Count 수정
  src/layout/Header/CartLinkList.jsx
Labels: 🦁 modify

#185 🦁 modify : Header 링크 리스트 패딩 부여/매장찾기 검색 폼 모바일
  README.md
  src/components/FindStoreSearchForm.jsx
  src/components/LogoLinks.jsx
  src/layout/Header/DesktopHeader.jsx
Labels: 🦁 modify

#186 ✨ feat : 이벤트 페이지 검색기능 구현
  src/components/Event/EventSearchForm.jsx
  src/components/Event/EventTab.jsx
  src/components/Event/TabContents.jsx
Labels: ✨ feat, 💙 react

#187 vite.config.js 추가 설정
  vite.config.js
Labels: 💙 react
